apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app-deployment
  namespace: login-app
  labels:
    app: django-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-login-app
  template:
    metadata:
      labels:
        app: django-login-app
    spec:
      containers:
      - name: login-app
        image: 542279893489.dkr.ecr.us-east-1.amazonaws.com/login-app:latest
        ports:
        - containerPort: 80